export const best_response = {
  BODY_Q_APPEARANCE_DISTRESS_Q01: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q02: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q03: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q04: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q05: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q06: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q07: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q08: 1,
}

export const worst_response = {
  BODY_Q_APPEARANCE_DISTRESS_Q01: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q02: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q03: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q04: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q05: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q06: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q07: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q08: 4,
}

export const random_response = {
  BODY_Q_APPEARANCE_DISTRESS_Q01: 2,
  BODY_Q_APPEARANCE_DISTRESS_Q02: 3,
  BODY_Q_APPEARANCE_DISTRESS_Q03: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q04: 2,
  BODY_Q_APPEARANCE_DISTRESS_Q05: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q06: 3,
  BODY_Q_APPEARANCE_DISTRESS_Q07: 2,
  BODY_Q_APPEARANCE_DISTRESS_Q08: 1,
}

/**
 * 5 of 8 answered (3 missing < 50% threshold of 4).
 * Mean of [2,3,1,4,2] = 2.4 → imputed sum = 19.2 → round = 19 → Rasch = 50
 */
export const partial_response = {
  BODY_Q_APPEARANCE_DISTRESS_Q01: 2,
  BODY_Q_APPEARANCE_DISTRESS_Q02: 3,
  BODY_Q_APPEARANCE_DISTRESS_Q03: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q04: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q05: 2,
  BODY_Q_APPEARANCE_DISTRESS_Q06: undefined,
  BODY_Q_APPEARANCE_DISTRESS_Q07: undefined,
  BODY_Q_APPEARANCE_DISTRESS_Q08: undefined,
}

/**
 * 4 of 8 answered (4 missing >= 50% threshold of 4) → null
 */
export const too_many_missing_response = {
  BODY_Q_APPEARANCE_DISTRESS_Q01: 1,
  BODY_Q_APPEARANCE_DISTRESS_Q02: 2,
  BODY_Q_APPEARANCE_DISTRESS_Q03: 3,
  BODY_Q_APPEARANCE_DISTRESS_Q04: 4,
  BODY_Q_APPEARANCE_DISTRESS_Q05: undefined,
  BODY_Q_APPEARANCE_DISTRESS_Q06: undefined,
  BODY_Q_APPEARANCE_DISTRESS_Q07: undefined,
  BODY_Q_APPEARANCE_DISTRESS_Q08: undefined,
}
