import { z } from 'zod'
import { type ScoreInputSchemaType } from '../../../types/ScoreInput.types'

const type = {
  type: z
    .union([
      z.literal(1),
      z.literal(2),
      z.literal(3),
      z.literal(4),
      z.literal(5),
    ])
    .optional(),
}

export const SCL90_INPUTS = {
  Q01: { ...type },
  Q02: { ...type },
  Q03: { ...type },
  Q04: { ...type },
  Q05: { ...type },
  Q06: { ...type },
  Q07: { ...type },
  Q08: { ...type },
  Q09: { ...type },
  Q10: { ...type },
  Q11: { ...type },
  Q12: { ...type },
  Q13: { ...type },
  Q14: { ...type },
  Q15: { ...type },
  Q16: { ...type },
  Q17: { ...type },
  Q18: { ...type },
  Q19: { ...type },
  Q20: { ...type },
  Q21: { ...type },
  Q22: { ...type },
  Q23: { ...type },
  Q24: { ...type },
  Q25: { ...type },
  Q26: { ...type },
  Q27: { ...type },
  Q28: { ...type },
  Q29: { ...type },
  Q30: { ...type },
  Q31: { ...type },
  Q32: { ...type },
  Q33: { ...type },
  Q34: { ...type },
  Q35: { ...type },
  Q36: { ...type },
  Q37: { ...type },
  Q38: { ...type },
  Q39: { ...type },
  Q40: { ...type },
  Q41: { ...type },
  Q42: { ...type },
  Q43: { ...type },
  Q44: { ...type },
  Q45: { ...type },
  Q46: { ...type },
  Q47: { ...type },
  Q48: { ...type },
  Q49: { ...type },
  Q50: { ...type },
  Q51: { ...type },
  Q52: { ...type },
  Q53: { ...type },
  Q54: { ...type },
  Q55: { ...type },
  Q56: { ...type },
  Q57: { ...type },
  Q58: { ...type },
  Q59: { ...type },
  Q60: { ...type },
  Q61: { ...type },
  Q62: { ...type },
  Q63: { ...type },
  Q64: { ...type },
  Q65: { ...type },
  Q66: { ...type },
  Q67: { ...type },
  Q68: { ...type },
  Q69: { ...type },
  Q70: { ...type },
  Q71: { ...type },
  Q72: { ...type },
  Q73: { ...type },
  Q74: { ...type },
  Q75: { ...type },
  Q76: { ...type },
  Q77: { ...type },
  Q78: { ...type },
  Q79: { ...type },
  Q80: { ...type },
  Q81: { ...type },
  Q82: { ...type },
  Q83: { ...type },
  Q84: { ...type },
  Q85: { ...type },
  Q86: { ...type },
  Q87: { ...type },
  Q88: { ...type },
  Q89: { ...type },
  Q90: { ...type },
} satisfies ScoreInputSchemaType
