export type SubscaleType =
  | 'QUICKDASH_SCORE'
  | 'WORK_MODULE'
  | 'SPORTS_PERFORMING_ARTS_MODULE'

export const QUICKDASH_SUBSCALES: Record<SubscaleType, string[]> = {
  QUICKDASH_SCORE: [
    'QUICKDASH_Q01',
    'QUICKDASH_Q02',
    'QUICKDASH_Q03',
    'QUICKDASH_Q04',
    'QUICKDASH_Q05',
    'QUICKDASH_Q06',
    'QUICKDASH_Q07',
    'QUICKDASH_Q08',
    'QUICKDASH_Q09',
    'QUICKDASH_Q10',
    'QUICKDASH_Q11',
  ],
  WORK_MODULE: [
    'QUICKDASH_WORK_MODULE_Q01',
    'QUICKDASH_WORK_MODULE_Q02',
    'QUICKDASH_WORK_MODULE_Q03',
    'QUICKDASH_WORK_MODULE_Q04',
  ],
  SPORTS_PERFORMING_ARTS_MODULE: [
    'QUICKDASH_SPORTS_PERFORMING_ARTS_MODULE_Q01',
    'QUICKDASH_SPORTS_PERFORMING_ARTS_MODULE_Q02',
    'QUICKDASH_SPORTS_PERFORMING_ARTS_MODULE_Q03',
    'QUICKDASH_SPORTS_PERFORMING_ARTS_MODULE_Q04',
  ],
}
