export const CORE_OM_SUBSCALE_ITEMS = {
  SUBJECTIVE_WELLBEING: [
    'CORE_OM_Q04',
    'CORE_OM_Q14',
    'CORE_OM_Q17',
    'CORE_OM_Q31',
  ],
  PROBLEMS_SYMPTOMS: [
    'CORE_OM_Q02',
    'CORE_OM_Q05',
    'CORE_OM_Q08',
    'CORE_OM_Q11',
    'CORE_OM_Q13',
    'CORE_OM_Q15',
    'CORE_OM_Q18',
    'CORE_OM_Q20',
    'CORE_OM_Q23',
    'CORE_OM_Q27',
    'CORE_OM_Q28',
    'CORE_OM_Q30',
  ],
  LIFE_FUNCTIONING_DIFFICULTIES: [
    'CORE_OM_Q01',
    'CORE_OM_Q03',
    'CORE_OM_Q07',
    'CORE_OM_Q10',
    'CORE_OM_Q12',
    'CORE_OM_Q19',
    'CORE_OM_Q21',
    'CORE_OM_Q25',
    'CORE_OM_Q26',
    'CORE_OM_Q29',
    'CORE_OM_Q32',
    'CORE_OM_Q33',
  ],
  RISK_HARM: [
    'CORE_OM_Q09',
    'CORE_OM_Q06',
    'CORE_OM_Q16',
    'CORE_OM_Q22',
    'CORE_OM_Q24',
    'CORE_OM_Q34',
  ],
}
