export type DomainType =
  | 'HEAD'
  | 'EYES'
  | 'EARS'
  | 'NOSE'
  | 'MOUTH_THROAT'
  | 'SKIN'
  | 'HEART'
  | 'LUNGS'
  | 'DIGESTIVE_TRACT'
  | 'JOINTS_MUSCLE'
  | 'WEIGHT'
  | 'ENERGY_ACTIVITY'
  | 'MIND'
  | 'EMOTIONS'
  | 'OTHER'

export const MSQ_DOMAINS: Record<DomainType, string[]> = {
  HEAD: [
    'HEAD_Q01_HEADACHES',
    'HEAD_Q02_FAINTNESS',
    'HEAD_Q03_DIZZINESS',
    'HEAD_Q04_INSOMNIA',
  ],
  EYES: [
    'EYES_Q01_WATERY_OR_ITCHY_EYES',
    'EYES_Q02_SWOLLEN_REDDENED_OR_STICKY_EYELIDS',
    'EYES_Q03_BAGS_OR_DARK_CIRCLES_UNDER_EYES',
    'EYES_Q04_BLURRED_OR_TUNNEL_VISION',
  ],
  EARS: [
    'EARS_Q01_ITCHY_EARS',
    'EARS_Q02_EARACHES_EAR_INFECTIONS',
    'EARS_Q03_DRAINAGE_FROM_EAR',
    'EARS_Q04_RINGING_EARS_HEARING_LOSS',
  ],
  NOSE: [
    'NOSE_Q01_STUFFY_NOSE',
    'NOSE_Q02_SINUS_PROBLEMS',
    'NOSE_Q03_HAY_FEVER',
    'NOSE_Q04_SNEEZING_ATTACKS',
    'NOSE_Q05_EXCESSIVE_MUCUS_FORMATION',
  ],
  MOUTH_THROAT: [
    'MOUTH_THROAT_Q01_CHRONIC_COUGHING',
    'MOUTH_THROAT_Q02_GAGGING_FREQUENT_NEED_TO_CLEAR_THROAT',
    'MOUTH_THROAT_Q03_SORE_THROAT_HOARSENESS_LOSS_OF_VOUICE',
    'MOUTH_THROAT_Q04_SWOLLEN_OR_DISCOLORED_TONGUE_GUMS_LIPS',
    'MOUTH_THROAT_Q05_CANKER_SORES',
  ],
  SKIN: [
    'SKIN_Q01_ACNE',
    'SKIN_Q02_HIVES_RASHES_DRY_SKIN',
    'SKIN_Q03_HAIR_LOSS',
    'SKIN_Q04_FLUSHING_HOT_FLASHES',
    'SKIN_Q05_EXCESSIVE_SWEATING',
  ],
  HEART: [
    'HEART_Q01_IRREGULAR_OR_SKIPPED_HEARTBEAT',
    'HEART_Q02_RAPID_OR_POUNDING_HEARTBEAT',
    'HEART_Q03_CHEST_PAIN',
  ],
  LUNGS: [
    'LUNGS_Q01_CHEST_CONGESTION',
    'LUNGS_Q02_ASTHMA_BRONCHITIS',
    'LUNGS_Q03_SHORTNESS_OF_BREATH',
    'LUNGS_Q04_DIFFICULTY_BREATHING',
  ],
  DIGESTIVE_TRACT: [
    'DIGESTIVE_TRACT_Q01_NAUSEA_VOMITING',
    'DIGESTIVE_TRACT_Q02_DIARRHEA',
    'DIGESTIVE_TRACT_Q03_CONSTIPATION',
    'DIGESTIVE_TRACT_Q04_BLOATED_FEELING',
    'DIGESTIVE_TRACT_Q05_BELCHING_PASSING_GAS',
    'DIGESTIVE_TRACT_Q06_HEARTBURN',
    'DIGESTIVE_TRACT_Q07_INTESTINAL_STOMACH_PAIN',
  ],
  JOINTS_MUSCLE: [
    'JOINTS_MUSCLE_Q01_PAIN_OR_ACHES_IN_JOINTS',
    'JOINTS_MUSCLE_Q02_ARTHRITIS',
    'JOINTS_MUSCLE_Q03_STIFFNESS_OR_LIMITATION_OF_MOVEMENT',
    'JOINTS_MUSCLE_Q04_PAIN_OR_ACHES_IN_MUSCLES',
    'JOINTS_MUSCLE_Q05_FEELING_OF_WEAKNESS_OR_TIREDNESS',
  ],
  WEIGHT: [
    'WEIGHT_Q01_BINGE_EATING_DRINKING',
    'WEIGHT_Q02_CRAVING_CERTAIN_FOODS',
    'WEIGHT_Q03_EXCESSIVE_WEIGHT',
    'WEIGHT_Q04_COMPULSIVE_EATING',
    'WEIGHT_Q05_WATER_RETENTION',
    'WEIGHT_Q06_UNDERWEIGHT',
  ],
  ENERGY_ACTIVITY: [
    'ENERGY_ACTIVITY_Q01_FATIGUE_SLUGGISHNESS',
    'ENERGY_ACTIVITY_Q02_APATHY_LETHARGY',
    'ENERGY_ACTIVITY_Q03_HYPERACTIVITY',
    'ENERGY_ACTIVITY_Q04_RESTLESSNESS',
  ],
  MIND: [
    'MIND_Q01_POOR_MEMORY',
    'MIND_Q02_CONFUSION_POOR_COMPREHENSION',
    'MIND_Q03_POOR_CONCENTRATION',
    'MIND_Q04_POOR_PHYSICAL_COORDINATION',
    'MIND_Q05_DIFFICULTY_IN_MAKING_DECISIONS',
    'MIND_Q06_STUTTERING_OR_STAMMERING',
    'MIND_Q07_SLURRED_SPEECH',
    'MIND_Q08_LEARNING_DISABILITIES',
  ],
  EMOTIONS: [
    'EMOTIONS_Q01_MOOD_SWINGS',
    'EMOTIONS_Q02_ANXIETY_FEAR_NERVOUSNESS',
    'EMOTIONS_Q03_ANGER_IRRITABILITY_AGGRESSIVENESS',
    'EMOTIONS_Q04_DEPRESSION',
  ],
  OTHER: [
    'OTHER_Q01_FREQUENT_ILLNESS',
    'OTHER_Q02_FREQUENT_OR_URGENT_URINATION',
    'OTHER_Q03_GENITAL_ITCH_OR_DISCHARGE',
  ],
}
