export const best_response = {
  PAIN: 44,
  LIMP: 11,
  SUPPORT: 11,
  DISTANCE_WALKED: 11,
  SITTING: 5,
  ENTER_PUBLIC_TRANSPORTATION: 1,
  STAIRS: 4,
  PUT_ON_SOCKS_AND_SHOES: 4,
  ABSENCE_OF_DEFORMITY: [1, 2, 3, 4],
  RANGE_OF_MOTION_FLEXION: 140,
  RANGE_OF_MOTION_ABDUCTION: 40,
  RANGE_OF_MOTION_ADDUCTION: 40,
  RANGE_OF_MOTION_EXTERNAL_ROTATION: 40,
  RANGE_OF_MOTION_INTERNAL_ROTATION: 40,
}

export const worst_response = {
  PAIN: 0,
  LIMP: 0,
  SUPPORT: 0,
  DISTANCE_WALKED: 0,
  SITTING: 0,
  ENTER_PUBLIC_TRANSPORTATION: 0,
  STAIRS: 0,
  PUT_ON_SOCKS_AND_SHOES: 0,
  ABSENCE_OF_DEFORMITY: [],
  RANGE_OF_MOTION_FLEXION: 0,
  RANGE_OF_MOTION_ABDUCTION: 0,
  RANGE_OF_MOTION_ADDUCTION: 0,
  RANGE_OF_MOTION_EXTERNAL_ROTATION: 0,
  RANGE_OF_MOTION_INTERNAL_ROTATION: 0,
}

/**
 * Expected scores:
 * - Range of motion score: 44
 * - Harris hip score: 3
 */
export const random_response = {
  PAIN: 20,
  LIMP: 5,
  SUPPORT: 2,
  DISTANCE_WALKED: 8,
  SITTING: 0,
  ENTER_PUBLIC_TRANSPORTATION: 0,
  STAIRS: 2,
  PUT_ON_SOCKS_AND_SHOES: 4,
  ABSENCE_OF_DEFORMITY: [1, 2],
  RANGE_OF_MOTION_FLEXION: 70,
  RANGE_OF_MOTION_ABDUCTION: 20,
  RANGE_OF_MOTION_ADDUCTION: 10,
  RANGE_OF_MOTION_EXTERNAL_ROTATION: 15,
  RANGE_OF_MOTION_INTERNAL_ROTATION: 5,
}
