// @flow
export const min_response = {
  PAIN_WALKING: 0,
  PAIN_STAIR_CLIMBING: 0,
  PAIN_NOCTURNAL: 0,
  PAIN_REST: 0,
  PAIN_WEIGHT_BEARING: 0,
  STIFFNESS_MORNING: 0,
  STIFFNESS_LATER: 0,
  PHYSICAL_FUNCTION_DESCENDING_STAIRS: 0,
  PHYSICAL_FUNCTION_ASCENDING_STAIRS: 0,
  PHYSICAL_FUNCTION_RISING_FROM_SITTING: 0,
  PHYSICAL_FUNCTION_STANDING: 0,
  PHYSICAL_FUNCTION_BENDING: 0,
  PHYSICAL_FUNCTION_WALKING_FLAT_SURFACE: 0,
  PHYSICAL_FUNCTION_GETTING_IN_OUT_CAR: 0,
  PHYSICAL_FUNCTION_SHOPPING: 0,
  PHYSICAL_FUNCTION_PUTTING_ON_SOCKS: 0,
  PHYSICAL_FUNCTION_LYING_BED: 0,
  PHYSICAL_FUNCTION_TAKING_OFF_SOCKS: 0,
  PHYSICAL_FUNCTION_RISING_BED: 0,
  PHYSICAL_FUNCTION_GETTING_IN_OUT_BATH: 0,
  PHYSICAL_FUNCTION_SITTING: 0,
  PHYSICAL_FUNCTION_GETTING_ON_OFF_TOILET: 0,
  PHYSICAL_FUNCTION_HEAVY_DOMESTIC_DUTIES: 0,
  PHYSICAL_FUNCTION_LIGHT_DOMESTIC_DUTIES: 0
}

export const median_response = {
  PAIN_WALKING: 2,
  PAIN_STAIR_CLIMBING: 2,
  PAIN_NOCTURNAL: 2,
  PAIN_REST: 2,
  PAIN_WEIGHT_BEARING: 2,
  STIFFNESS_MORNING: 2,
  STIFFNESS_LATER: 2,
  PHYSICAL_FUNCTION_DESCENDING_STAIRS: 2,
  PHYSICAL_FUNCTION_ASCENDING_STAIRS: 2,
  PHYSICAL_FUNCTION_RISING_FROM_SITTING: 2,
  PHYSICAL_FUNCTION_STANDING: 2,
  PHYSICAL_FUNCTION_BENDING: 2,
  PHYSICAL_FUNCTION_WALKING_FLAT_SURFACE: 2,
  PHYSICAL_FUNCTION_GETTING_IN_OUT_CAR: 2,
  PHYSICAL_FUNCTION_SHOPPING: 2,
  PHYSICAL_FUNCTION_PUTTING_ON_SOCKS: 2,
  PHYSICAL_FUNCTION_LYING_BED: 2,
  PHYSICAL_FUNCTION_TAKING_OFF_SOCKS: 2,
  PHYSICAL_FUNCTION_RISING_BED: 2,
  PHYSICAL_FUNCTION_GETTING_IN_OUT_BATH: 2,
  PHYSICAL_FUNCTION_SITTING: 2,
  PHYSICAL_FUNCTION_GETTING_ON_OFF_TOILET: 2,
  PHYSICAL_FUNCTION_HEAVY_DOMESTIC_DUTIES: 2,
  PHYSICAL_FUNCTION_LIGHT_DOMESTIC_DUTIES: 2
}

export const max_response = {
  PAIN_WALKING: 4,
  PAIN_STAIR_CLIMBING: 4,
  PAIN_NOCTURNAL: 4,
  PAIN_REST: 4,
  PAIN_WEIGHT_BEARING: 4,
  STIFFNESS_MORNING: 4,
  STIFFNESS_LATER: 4,
  PHYSICAL_FUNCTION_DESCENDING_STAIRS: 4,
  PHYSICAL_FUNCTION_ASCENDING_STAIRS: 4,
  PHYSICAL_FUNCTION_RISING_FROM_SITTING: 4,
  PHYSICAL_FUNCTION_STANDING: 4,
  PHYSICAL_FUNCTION_BENDING: 4,
  PHYSICAL_FUNCTION_WALKING_FLAT_SURFACE: 4,
  PHYSICAL_FUNCTION_GETTING_IN_OUT_CAR: 4,
  PHYSICAL_FUNCTION_SHOPPING: 4,
  PHYSICAL_FUNCTION_PUTTING_ON_SOCKS: 4,
  PHYSICAL_FUNCTION_LYING_BED: 4,
  PHYSICAL_FUNCTION_TAKING_OFF_SOCKS: 4,
  PHYSICAL_FUNCTION_RISING_BED: 4,
  PHYSICAL_FUNCTION_GETTING_IN_OUT_BATH: 4,
  PHYSICAL_FUNCTION_SITTING: 4,
  PHYSICAL_FUNCTION_GETTING_ON_OFF_TOILET: 4,
  PHYSICAL_FUNCTION_HEAVY_DOMESTIC_DUTIES: 4,
  PHYSICAL_FUNCTION_LIGHT_DOMESTIC_DUTIES: 4
}

/**
 * PART A = 14
 * PART B = 7.5
 * TOTAL = 4.3
 */
export const random_response = {
  Q1: 2,
  Q2: 7,
  Q3: 1,
  Q4: 4,
  Q5: 9,
  Q6: 6
}
