// @flow
import {
  FIFTEEN,
  FIVE,
  FOUR,
  SIX,
  TEN,
  THREE,
  TWENTY,
  TWENTY_FIVE,
  TWO,
  ZERO
} from '../definition/mlks_inputs'

export const best_response = {
  Q01_LIMP: FIVE,
  Q02_CANE_OR_CRUTCHES: FIVE,
  Q03_LOCKING_KNEE: FIFTEEN,
  Q04_GIVING_WAY_SENSATION_KNEE: TWENTY_FIVE,
  Q05_PAIN: TWENTY_FIVE,
  Q06_SWELLING: TEN,
  Q07_CLIMBING_STAIRS: TEN,
  Q08_SQUATTING: FIVE
}

export const median_response = {
  Q01_LIMP: THREE,
  Q02_CANE_OR_CRUTCHES: TWO,
  Q03_LOCKING_KNEE: SIX,
  Q04_GIVING_WAY_SENSATION_KNEE: FIFTEEN,
  Q05_PAIN: TEN,
  Q06_SWELLING: SIX,
  Q07_CLIMBING_STAIRS: TWO,
  Q08_SQUATTING: FOUR
}

export const worst_response = {
  Q01_LIMP: ZERO,
  Q02_CANE_OR_CRUTCHES: ZERO,
  Q03_LOCKING_KNEE: ZERO,
  Q04_GIVING_WAY_SENSATION_KNEE: ZERO,
  Q05_PAIN: ZERO,
  Q06_SWELLING: ZERO,
  Q07_CLIMBING_STAIRS: ZERO,
  Q08_SQUATTING: ZERO
}

export const random_response = {
  Q01_LIMP: ZERO,
  Q02_CANE_OR_CRUTCHES: TWO,
  Q03_LOCKING_KNEE: SIX,
  Q04_GIVING_WAY_SENSATION_KNEE: TWENTY,
  Q05_PAIN: TWENTY_FIVE,
  Q06_SWELLING: ZERO,
  Q07_CLIMBING_STAIRS: SIX,
  Q08_SQUATTING: TWO
}
