export const min_response = {
  PDQ_8_MOBILITY: 0,
  PDQ_8_ADL: 0,
  PDQ_8_EMOTIONAL_WELLBEING: 0,
  PDQ_8_STIGMA: 0,
  PDQ_8_SOCIAL_SUPPORT: 0,
  PDQ_8_COGNITIONS: 0,
  PDQ_8_COMMUNICATIONS: 0,
  PDQ_8_BODILY_DISCOMFORT: 0,
}

export const median_response = {
  PDQ_8_MOBILITY: 2,
  PDQ_8_ADL: 2,
  PDQ_8_EMOTIONAL_WELLBEING: 2,
  PDQ_8_STIGMA: 2,
  PDQ_8_SOCIAL_SUPPORT: 2,
  PDQ_8_COGNITIONS: 2,
  PDQ_8_COMMUNICATIONS: 2,
  PDQ_8_BODILY_DISCOMFORT: 2,
}

export const max_response = {
  PDQ_8_MOBILITY: 4,
  PDQ_8_ADL: 4,
  PDQ_8_EMOTIONAL_WELLBEING: 4,
  PDQ_8_STIGMA: 4,
  PDQ_8_SOCIAL_SUPPORT: 4,
  PDQ_8_COGNITIONS: 4,
  PDQ_8_COMMUNICATIONS: 4,
  PDQ_8_BODILY_DISCOMFORT: 4,
}

/**
 * Expected score = 17/32 (53,125%)
 */
export const random_response = {
  PDQ_8_MOBILITY: 2,
  PDQ_8_ADL: 1,
  PDQ_8_EMOTIONAL_WELLBEING: 0,
  PDQ_8_STIGMA: 4,
  PDQ_8_SOCIAL_SUPPORT: 4,
  PDQ_8_COGNITIONS: 3,
  PDQ_8_COMMUNICATIONS: 1,
  PDQ_8_BODILY_DISCOMFORT: 2,
}
