export const min_response = {
  MINI_BEST_TEST_Q1: 0,
  MINI_BEST_TEST_Q2: 0,
  MINI_BEST_TEST_Q3_LEFT: 0,
  MINI_BEST_TEST_Q3_RIGHT: 0,
  MINI_BEST_TEST_Q4: 0,
  MINI_BEST_TEST_Q5: 0,
  MINI_BEST_TEST_Q6_LEFT: 0,
  MINI_BEST_TEST_Q6_RIGHT: 0,
  MINI_BEST_TEST_Q7: 0,
  MINI_BEST_TEST_Q8: 0,
  MINI_BEST_TEST_Q9: 0,
  MINI_BEST_TEST_Q10: 0,
  MINI_BEST_TEST_Q11: 0,
  MINI_BEST_TEST_Q12: 0,
  MINI_BEST_TEST_Q13: 0,
  MINI_BEST_TEST_Q14: 0,
}

export const median_response = {
  MINI_BEST_TEST_Q1: 1,
  MINI_BEST_TEST_Q2: 1,
  MINI_BEST_TEST_Q3_LEFT: 1,
  MINI_BEST_TEST_Q3_RIGHT: 1,
  MINI_BEST_TEST_Q4: 1,
  MINI_BEST_TEST_Q5: 1,
  MINI_BEST_TEST_Q6_LEFT: 1,
  MINI_BEST_TEST_Q6_RIGHT: 1,
  MINI_BEST_TEST_Q7: 1,
  MINI_BEST_TEST_Q8: 1,
  MINI_BEST_TEST_Q9: 1,
  MINI_BEST_TEST_Q10: 1,
  MINI_BEST_TEST_Q11: 1,
  MINI_BEST_TEST_Q12: 1,
  MINI_BEST_TEST_Q13: 1,
  MINI_BEST_TEST_Q14: 1,
}

export const max_response = {
  MINI_BEST_TEST_Q1: 2,
  MINI_BEST_TEST_Q2: 2,
  MINI_BEST_TEST_Q3_LEFT: 2,
  MINI_BEST_TEST_Q3_RIGHT: 2,
  MINI_BEST_TEST_Q4: 2,
  MINI_BEST_TEST_Q5: 2,
  MINI_BEST_TEST_Q6_LEFT: 2,
  MINI_BEST_TEST_Q6_RIGHT: 2,
  MINI_BEST_TEST_Q7: 2,
  MINI_BEST_TEST_Q8: 2,
  MINI_BEST_TEST_Q9: 2,
  MINI_BEST_TEST_Q10: 2,
  MINI_BEST_TEST_Q11: 2,
  MINI_BEST_TEST_Q12: 2,
  MINI_BEST_TEST_Q13: 2,
  MINI_BEST_TEST_Q14: 2,
}

/**
 * Expected scores:
 * - Anticipatory postural adjustments [1, 3]: 3
 * - Reactive postural control [4, 6]: 2
 * - Sensory orientation [7, 9]: 3
 * - Dynamic gait [10, 14]: 5
 * - Total score [1, 14]: 13
 */
export const random_response = {
  MINI_BEST_TEST_Q1: 1,
  MINI_BEST_TEST_Q2: 2,
  MINI_BEST_TEST_Q3_LEFT: 0,
  MINI_BEST_TEST_Q3_RIGHT: 2,
  MINI_BEST_TEST_Q4: 0,
  MINI_BEST_TEST_Q5: 1,
  MINI_BEST_TEST_Q6_LEFT: 1,
  MINI_BEST_TEST_Q6_RIGHT: 1,
  MINI_BEST_TEST_Q7: 2,
  MINI_BEST_TEST_Q8: 1,
  MINI_BEST_TEST_Q9: 0,
  MINI_BEST_TEST_Q10: 0,
  MINI_BEST_TEST_Q11: 0,
  MINI_BEST_TEST_Q12: 2,
  MINI_BEST_TEST_Q13: 1,
  MINI_BEST_TEST_Q14: 2,
}
