export const best_response = {
  PANSS_6_Q01_DELUSIONS: 1,
  PANSS_6_Q02_CONCEPTUAL_DISORGANIZATIONS: 1,
  PANSS_6_Q03_HALLUCINATORY_BEHAVIOR: 1,
  PANSS_6_Q04_BLUNTED_AFFECT: 1,
  PANSS_6_Q05_PASSIVE_SOCIAL_WITHDRAWAL: 1,
  PANSS_6_Q06_LACK_OF_SPONTANEITY: 1,
}

export const median_response = {
  PANSS_6_Q01_DELUSIONS: 4,
  PANSS_6_Q02_CONCEPTUAL_DISORGANIZATIONS: 4,
  PANSS_6_Q03_HALLUCINATORY_BEHAVIOR: 4,
  PANSS_6_Q04_BLUNTED_AFFECT: 4,
  PANSS_6_Q05_PASSIVE_SOCIAL_WITHDRAWAL: 4,
  PANSS_6_Q06_LACK_OF_SPONTANEITY: 4,
}

export const worst_response = {
  PANSS_6_Q01_DELUSIONS: 7,
  PANSS_6_Q02_CONCEPTUAL_DISORGANIZATIONS: 7,
  PANSS_6_Q03_HALLUCINATORY_BEHAVIOR: 7,
  PANSS_6_Q04_BLUNTED_AFFECT: 7,
  PANSS_6_Q05_PASSIVE_SOCIAL_WITHDRAWAL: 7,
  PANSS_6_Q06_LACK_OF_SPONTANEITY: 7,
}

/**
 * Total = 21
 * Positive = 5
 * Negative = 16
 */
export const random_response = {
  PANSS_6_Q01_DELUSIONS: 1,
  PANSS_6_Q02_CONCEPTUAL_DISORGANIZATIONS: 2,
  PANSS_6_Q03_HALLUCINATORY_BEHAVIOR: 2,
  PANSS_6_Q04_BLUNTED_AFFECT: 4,
  PANSS_6_Q05_PASSIVE_SOCIAL_WITHDRAWAL: 5,
  PANSS_6_Q06_LACK_OF_SPONTANEITY: 7,
}
