import type { InputType } from '../../../../types/calculations.types'
import { NumberInputType } from '../../../../types/calculations/inputs/calculation-inputs.types'

export const input_type: NumberInputType = {
  type: 'number',
  allowed_answers: [
    { value: 1 },
    { value: 2 },
    { value: 3 },
    { value: 4 },
    { value: 5 },
  ],
}

export const PAQ_Q_INPUTS: Array<InputType> = [
  { input_id: 'ITEM_1_ACTIVITY_01', input_type },
  { input_id: 'ITEM_1_ACTIVITY_02', input_type },
  { input_id: 'ITEM_1_ACTIVITY_03', input_type },
  { input_id: 'ITEM_1_ACTIVITY_04', input_type },
  { input_id: 'ITEM_1_ACTIVITY_05', input_type },
  { input_id: 'ITEM_1_ACTIVITY_06', input_type },
  { input_id: 'ITEM_1_ACTIVITY_07', input_type },
  { input_id: 'ITEM_1_ACTIVITY_08', input_type },
  { input_id: 'ITEM_1_ACTIVITY_09', input_type },
  { input_id: 'ITEM_1_ACTIVITY_10', input_type },
  { input_id: 'ITEM_1_ACTIVITY_11', input_type },
  { input_id: 'ITEM_1_ACTIVITY_12', input_type },
  { input_id: 'ITEM_1_ACTIVITY_13', input_type },
  { input_id: 'ITEM_1_ACTIVITY_14', input_type },
  { input_id: 'ITEM_1_ACTIVITY_15', input_type },
  { input_id: 'ITEM_1_ACTIVITY_16', input_type },
  { input_id: 'ITEM_1_ACTIVITY_17', input_type },
  { input_id: 'ITEM_1_ACTIVITY_18', input_type },
  { input_id: 'ITEM_1_ACTIVITY_19', input_type },
  { input_id: 'ITEM_1_ACTIVITY_20', input_type },
  { input_id: 'ITEM_1_ACTIVITY_21', input_type },
  { input_id: 'ITEM_1_ACTIVITY_22', input_type },
  { input_id: 'ITEM_1_ACTIVITY_23', input_type },
  { input_id: 'ITEM_1_ACTIVITY_24', input_type },
  { input_id: 'ITEM_1_ACTIVITY_25', input_type },
  { input_id: 'ITEM_2', input_type },
  { input_id: 'ITEM_3', input_type },
  { input_id: 'ITEM_4', input_type },
  { input_id: 'ITEM_5', input_type },
  { input_id: 'ITEM_6', input_type },
  { input_id: 'ITEM_7', input_type },
  { input_id: 'ITEM_8', input_type },
  { input_id: 'ITEM_9_MONDAY', input_type },
  { input_id: 'ITEM_9_TUESDAY', input_type },
  { input_id: 'ITEM_9_WEDNESDAY', input_type },
  { input_id: 'ITEM_9_THURSDAY', input_type },
  { input_id: 'ITEM_9_FRIDAY', input_type },
  { input_id: 'ITEM_9_SATURDAY', input_type },
  { input_id: 'ITEM_9_SUNDAY', input_type },
]
