export type SectionType =
  | 'ANTICIPATORY_POSTURAL_ADJUSTEMENTS'
  | 'REACTIVE_POSTURAL_CONTROL'
  | 'SENSORY_ORIENTATION'
  | 'DYNAMIC_GAIT'

export const MINI_BEST_TEST_SECTIONS: Record<SectionType, string[]> = {
  ANTICIPATORY_POSTURAL_ADJUSTEMENTS: [
    'MINI_BEST_TEST_Q01',
    'MINI_BEST_TEST_Q02',
    'MINI_BEST_TEST_Q03_LEFT',
    'MINI_BEST_TEST_Q03_RIGHT',
  ],
  REACTIVE_POSTURAL_CONTROL: [
    'MINI_BEST_TEST_Q04',
    'MINI_BEST_TEST_Q05',
    'MINI_BEST_TEST_Q06_LEFT',
    'MINI_BEST_TEST_Q06_RIGHT',
  ],
  SENSORY_ORIENTATION: [
    'MINI_BEST_TEST_Q07',
    'MINI_BEST_TEST_Q08',
    'MINI_BEST_TEST_Q09',
  ],
  DYNAMIC_GAIT: [
    'MINI_BEST_TEST_Q10',
    'MINI_BEST_TEST_Q11',
    'MINI_BEST_TEST_Q12',
    'MINI_BEST_TEST_Q13',
    'MINI_BEST_TEST_Q14',
  ],
}
