export type ScaleType =
  | 'VISUOSPATIAL_EXECUTIVE'
  | 'NAMING'
  | 'ATTENTION'
  | 'LANGUAGE'
  | 'ABSTRACTION'
  | 'DELAYED_RECALL'
  | 'ORIENTATION'

export const MOCA_SCALES: Record<ScaleType, string[]> = {
  VISUOSPATIAL_EXECUTIVE: [
    'ALTERNATING_TRAIL_MARKING',
    'VISUOCONSTRUCTIONAL_SKILLS_CUBE',
    'VISUOCONSTRUCTIONAL_SKILLS_CLOCK',
  ],
  NAMING: ['NAMING'],
  ATTENTION: [
    'FORWARD_DIGIT_SPAN',
    'BACKWARD_DIGIT_SPAN',
    'VIGILANCE',
    'SERIAL_7S',
  ],
  LANGUAGE: ['SENTENCE_REPETITION', 'VERBAL_FLUENCY'],
  ABSTRACTION: ['ABSTRACTION'],
  DELAYED_RECALL: ['DELAYED_RECALL'],
  ORIENTATION: ['ORIENTATION'],
}
