// @flow
export const min_response = {
  OREBRO_DURATION: 1,
  OREBRO_PAIN_EXPERIENCE: 0,
  OREBRO_FEELING_DEPRESSED: 0,
  OREBRO_ANXIOUS: 0,
  OREBRO_RISK_OF_PERSISTENT_PAIN: 0,
  OREBRO_RETURN_TO_WORK_EXPECTANCY: 10, // inverse scoring
  OREBRO_PAIN_FEAR_AVOIDANCE: 0,
  OREBRO_NORMAL_WORK_WITH_PAIN: 0,
  OREBRO_LIGHT_WORK: 10, // inverse scoring
  OREBRO_SLEEP_AT_NIGHT: 10 // inverse scoring
}

export const median_response = {
  OREBRO_DURATION: 5,
  OREBRO_PAIN_EXPERIENCE: 5,
  OREBRO_FEELING_DEPRESSED: 5,
  OREBRO_ANXIOUS: 5,
  OREBRO_RISK_OF_PERSISTENT_PAIN: 5,
  OREBRO_RETURN_TO_WORK_EXPECTANCY: 5, // inverse scoring
  OREBRO_PAIN_FEAR_AVOIDANCE: 5,
  OREBRO_NORMAL_WORK_WITH_PAIN: 5,
  OREBRO_LIGHT_WORK: 5, // inverse scoring
  OREBRO_SLEEP_AT_NIGHT: 5 // inverse scoring
}

export const max_response = {
  OREBRO_DURATION: 10,
  OREBRO_PAIN_EXPERIENCE: 10,
  OREBRO_FEELING_DEPRESSED: 10,
  OREBRO_ANXIOUS: 10,
  OREBRO_RISK_OF_PERSISTENT_PAIN: 10,
  OREBRO_RETURN_TO_WORK_EXPECTANCY: 0, // inverse scoring
  OREBRO_PAIN_FEAR_AVOIDANCE: 10,
  OREBRO_NORMAL_WORK_WITH_PAIN: 10,
  OREBRO_LIGHT_WORK: 0, // inverse scoring
  OREBRO_SLEEP_AT_NIGHT: 0 // inverse scoring
}

/**
 * Score = 21
 */
export const random_response = {
  OREBRO_DURATION: 1,
  OREBRO_PAIN_EXPERIENCE: 0,
  OREBRO_FEELING_DEPRESSED: 4,
  OREBRO_ANXIOUS: 3,
  OREBRO_RISK_OF_PERSISTENT_PAIN: 1,
  OREBRO_RETURN_TO_WORK_EXPECTANCY: 5, // inverse scoring
  OREBRO_PAIN_FEAR_AVOIDANCE: 0,
  OREBRO_NORMAL_WORK_WITH_PAIN: 2,
  OREBRO_LIGHT_WORK: 6, // inverse scoring
  OREBRO_SLEEP_AT_NIGHT: 9 // inverse scoring
}
