import { scoring_value_to_numeric_value } from './pro_ctcae_calculation/scoring_value_to_numeric_value/scoring_value_to_numeric_value'

export const raw_scoring_table = [
  {
    FREQ: 'Never (0)',
    SEV: 'None (0)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'None (0)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'None (0)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'None (0)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'None (0)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'None (0)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Mild (1)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Mild (1)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Mild (1)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Mild (1)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Mild (1)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Moderate (2)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Moderate (2)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Moderate (2)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Moderate (2)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Moderate (2)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Severe (3)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Severe (3)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Severe (3)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Severe (3)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Severe (3)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Very Severe (4)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Very Severe (4)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Very Severe (4)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Very Severe (4)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Very Severe (4)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'None (0)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'None (0)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'None (0)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'None (0)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'None (0)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Mild (1)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Mild (1)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Mild (1)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Mild (1)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Mild (1)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Moderate (2)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Moderate (2)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Moderate (2)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Moderate (2)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Moderate (2)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Severe (3)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Severe (3)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Severe (3)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Severe (3)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Severe (3)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Very Severe (4)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Very Severe (4)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Very Severe (4)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Very Severe (4)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Very Severe (4)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'None (0)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'None (0)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'None (0)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'None (0)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'None (0)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Mild (1)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Mild (1)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Mild (1)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Mild (1)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Mild (1)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Moderate (2)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Moderate (2)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Moderate (2)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Moderate (2)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Moderate (2)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Severe (3)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Severe (3)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Severe (3)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Severe (3)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Severe (3)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Very Severe (4)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Very Severe (4)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Very Severe (4)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Very Severe (4)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Very Severe (4)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'None (0)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'None (0)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'None (0)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'None (0)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'None (0)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Mild (1)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Mild (1)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Mild (1)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Mild (1)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Mild (1)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Moderate (2)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Moderate (2)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Moderate (2)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Moderate (2)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Moderate (2)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Severe (3)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Severe (3)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Severe (3)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Severe (3)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Severe (3)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Very Severe (4)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Very Severe (4)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Very Severe (4)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Very Severe (4)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Very Severe (4)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Never (0)',
    SEV: 'None (0)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'None (0)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Mild (1)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Moderate (2)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Severe (3)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: 'Very Severe (4)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'None (0)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Mild (1)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Moderate (2)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Severe (3)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: 'Very Severe (4)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'None (0)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Mild (1)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Moderate (2)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Severe (3)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: 'Very Severe (4)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'None (0)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Mild (1)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Moderate (2)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Severe (3)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: 'Very Severe (4)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'None (0)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: '',
    SEV: 'Mild (1)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Mild (1)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Mild (1)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Mild (1)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Mild (1)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Moderate (2)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Moderate (2)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Moderate (2)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Moderate (2)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Moderate (2)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'Severe (3)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Severe (3)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Severe (3)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Severe (3)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'Severe (3)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'Very Severe (4)',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Very Severe (4)',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Very Severe (4)',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Very Severe (4)',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'Very Severe (4)',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Never (0)',
    SEV: '',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: '',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: '',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: '',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: '',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: '',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: '',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: '',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: '',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: '',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: '',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: '',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: '',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: '',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: '',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: '',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: '',
    INT: 'Not at all (0)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: '',
    INT: 'A little bit (1)',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: '',
    INT: 'Somewhat (2)',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: '',
    INT: 'Quite a bit (3)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: '',
    INT: 'Very Much (4)',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: 'Never (0)',
    SEV: '',
    INT: '',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: 'Rarely (1)',
    SEV: '',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Occasionally (2)',
    SEV: '',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: 'Frequently (3)',
    SEV: '',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: 'Almost Constantly (4)',
    SEV: '',
    INT: '',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'None (0)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 0,
  },
  {
    FREQ: '',
    SEV: 'Mild (1)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: 'Moderate (2)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: 'Severe (3)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: 'Very Severe (4)',
    INT: '',
    AMT: '',
    'Final Consensus Score': 3,
  },
  {
    FREQ: '',
    SEV: '',
    INT: '',
    AMT: 'Not at all (0)',
    'Final Consensus Score': 0,
  },
  {
    FREQ: '',
    SEV: '',
    INT: '',
    AMT: 'A little bit (1)',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: '',
    INT: '',
    AMT: 'Somewhat (2)',
    'Final Consensus Score': 1,
  },
  {
    FREQ: '',
    SEV: '',
    INT: '',
    AMT: 'Quite a bit (3)',
    'Final Consensus Score': 2,
  },
  {
    FREQ: '',
    SEV: '',
    INT: '',
    AMT: 'Very much (4)',
    'Final Consensus Score': 2,
  },
]

type PrettyScoringTableType = Array<{
  frequency?: number
  severity?: number
  impact?: number
  amt?: number
  score?: number
}>

export const pretty_scoring_table: PrettyScoringTableType =
  raw_scoring_table.map(input => {
    const { FREQ, SEV, INT, AMT } = input
    return {
      frequency: scoring_value_to_numeric_value(FREQ),
      severity: scoring_value_to_numeric_value(SEV),
      impact: scoring_value_to_numeric_value(INT),
      amt: scoring_value_to_numeric_value(AMT),
      score: input['Final Consensus Score'],
    }
  })
