// @flow

export const WOMAC_SECTIONS = {
  PAIN: [
    'PAIN_WALKING',
    'PAIN_STAIR_CLIMBING',
    'PAIN_NOCTURNAL',
    'PAIN_REST',
    'PAIN_WEIGHT_BEARING'
  ],
  STIFFNESS: ['STIFFNESS_MORNING', 'STIFFNESS_LATER'],
  DIFFICULTY: [
    'PHYSICAL_FUNCTION_DESCENDING_STAIRS',
    'PHYSICAL_FUNCTION_ASCENDING_STAIRS',
    'PHYSICAL_FUNCTION_RISING_FROM_SITTING',
    'PHYSICAL_FUNCTION_STANDING',
    'PHYSICAL_FUNCTION_BENDING',
    'PHYSICAL_FUNCTION_WALKING_FLAT_SURFACE',
    'PHYSICAL_FUNCTION_GETTING_IN_OUT_CAR',
    'PHYSICAL_FUNCTION_SHOPPING',
    'PHYSICAL_FUNCTION_PUTTING_ON_SOCKS',
    'PHYSICAL_FUNCTION_LYING_BED',
    'PHYSICAL_FUNCTION_TAKING_OFF_SOCKS',
    'PHYSICAL_FUNCTION_RISING_BED',
    'PHYSICAL_FUNCTION_GETTING_IN_OUT_BATH',
    'PHYSICAL_FUNCTION_SITTING',
    'PHYSICAL_FUNCTION_GETTING_ON_OFF_TOILET',
    'PHYSICAL_FUNCTION_HEAVY_DOMESTIC_DUTIES',
    'PHYSICAL_FUNCTION_LIGHT_DOMESTIC_DUTIES'
  ]
}
