export const best_response = {
  BODY_Q_PHYSICAL_FUNCTION_Q01: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q02: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q03: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q04: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q05: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q06: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q07: 1,
}

export const worst_response = {
  BODY_Q_PHYSICAL_FUNCTION_Q01: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q02: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q03: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q04: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q05: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q06: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q07: 4,
}

export const random_response = {
  BODY_Q_PHYSICAL_FUNCTION_Q01: 2,
  BODY_Q_PHYSICAL_FUNCTION_Q02: 3,
  BODY_Q_PHYSICAL_FUNCTION_Q03: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q04: 2,
  BODY_Q_PHYSICAL_FUNCTION_Q05: 4,
  BODY_Q_PHYSICAL_FUNCTION_Q06: 3,
  BODY_Q_PHYSICAL_FUNCTION_Q07: 2,
}

/**
 * 4 of 7 answered (3 missing < 50% threshold of 3.5).
 * Mean of [2,3,1,4] = 2.5 → imputed sum = 17.5 → round = 18 → Rasch = 50
 */
export const partial_response = {
  BODY_Q_PHYSICAL_FUNCTION_Q01: 2,
  BODY_Q_PHYSICAL_FUNCTION_Q02: 3,
  BODY_Q_PHYSICAL_FUNCTION_Q03: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q04: 4,
}

/**
 * 3 of 7 answered (4 missing >= 50% threshold of 3.5) → null
 */
export const too_many_missing_response = {
  BODY_Q_PHYSICAL_FUNCTION_Q01: 1,
  BODY_Q_PHYSICAL_FUNCTION_Q02: 2,
  BODY_Q_PHYSICAL_FUNCTION_Q03: 3,
}
