export const best_response = {
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q01: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q02: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q03: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q04: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q05: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q06: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q07: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q08: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q09: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q10: 1,
}

export const worst_response = {
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q01: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q02: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q03: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q04: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q05: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q06: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q07: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q08: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q09: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q10: 4,
}

export const random_response = {
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q01: 2,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q02: 3,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q03: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q04: 2,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q05: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q06: 3,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q07: 2,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q08: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q09: 3,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q10: 2,
}

/**
 * 6 of 10 answered (4 missing < 50% threshold of 5).
 * Mean of [2,3,1,4,2,3] = 2.5 → imputed sum = 25 → round = 25 → Rasch = 48
 */
export const partial_response = {
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q01: 2,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q02: 3,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q03: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q04: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q05: 2,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q06: 3,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q07: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q08: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q09: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q10: undefined,
}

/**
 * 5 of 10 answered (5 missing >= 50% threshold of 5) → null
 */
export const too_many_missing_response = {
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q01: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q02: 2,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q03: 3,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q04: 4,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q05: 1,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q06: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q07: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q08: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q09: undefined,
  BODY_Q_PSYCHOLOGICAL_FUNCTION_Q10: undefined,
}
