export const best_response = {
  BODY_Q_OFFICE_STAFF_Q01: 1,
  BODY_Q_OFFICE_STAFF_Q02: 1,
  BODY_Q_OFFICE_STAFF_Q03: 1,
  BODY_Q_OFFICE_STAFF_Q04: 1,
  BODY_Q_OFFICE_STAFF_Q05: 1,
  BODY_Q_OFFICE_STAFF_Q06: 1,
  BODY_Q_OFFICE_STAFF_Q07: 1,
  BODY_Q_OFFICE_STAFF_Q08: 1,
  BODY_Q_OFFICE_STAFF_Q09: 1,
  BODY_Q_OFFICE_STAFF_Q10: 1,
}

export const worst_response = {
  BODY_Q_OFFICE_STAFF_Q01: 4,
  BODY_Q_OFFICE_STAFF_Q02: 4,
  BODY_Q_OFFICE_STAFF_Q03: 4,
  BODY_Q_OFFICE_STAFF_Q04: 4,
  BODY_Q_OFFICE_STAFF_Q05: 4,
  BODY_Q_OFFICE_STAFF_Q06: 4,
  BODY_Q_OFFICE_STAFF_Q07: 4,
  BODY_Q_OFFICE_STAFF_Q08: 4,
  BODY_Q_OFFICE_STAFF_Q09: 4,
  BODY_Q_OFFICE_STAFF_Q10: 4,
}

export const random_response = {
  BODY_Q_OFFICE_STAFF_Q01: 2,
  BODY_Q_OFFICE_STAFF_Q02: 3,
  BODY_Q_OFFICE_STAFF_Q03: 1,
  BODY_Q_OFFICE_STAFF_Q04: 2,
  BODY_Q_OFFICE_STAFF_Q05: 4,
  BODY_Q_OFFICE_STAFF_Q06: 3,
  BODY_Q_OFFICE_STAFF_Q07: 2,
  BODY_Q_OFFICE_STAFF_Q08: 1,
  BODY_Q_OFFICE_STAFF_Q09: 3,
  BODY_Q_OFFICE_STAFF_Q10: 2,
}

/**
 * 3 out of 10 missing (< 50%) — mean imputation should apply.
 * Answered: [2,3,1,2,4,3,2] → sum=17, mean≈2.4286
 * Imputed total = round(17 + 3×2.4286) = round(24.286) = 24 → conversion 45
 */
export const partial_response = {
  BODY_Q_OFFICE_STAFF_Q01: 2,
  BODY_Q_OFFICE_STAFF_Q02: 3,
  BODY_Q_OFFICE_STAFF_Q03: 1,
  BODY_Q_OFFICE_STAFF_Q04: 2,
  BODY_Q_OFFICE_STAFF_Q05: 4,
  BODY_Q_OFFICE_STAFF_Q06: 3,
  BODY_Q_OFFICE_STAFF_Q07: 2,
}

/**
 * 5 out of 10 missing (≥ 50%) — should return null.
 */
export const half_missing_response = {
  BODY_Q_OFFICE_STAFF_Q01: 2,
  BODY_Q_OFFICE_STAFF_Q02: 3,
  BODY_Q_OFFICE_STAFF_Q03: 1,
  BODY_Q_OFFICE_STAFF_Q04: 2,
  BODY_Q_OFFICE_STAFF_Q05: 4,
}
