export const best_response = {
  BODY_Q_EATING_BEHAVIOR_Q01: 1,
  BODY_Q_EATING_BEHAVIOR_Q02: 1,
  BODY_Q_EATING_BEHAVIOR_Q03: 1,
  BODY_Q_EATING_BEHAVIOR_Q04: 1,
  BODY_Q_EATING_BEHAVIOR_Q05: 1,
  BODY_Q_EATING_BEHAVIOR_Q06: 1,
  BODY_Q_EATING_BEHAVIOR_Q07: 1,
  BODY_Q_EATING_BEHAVIOR_Q08: 1,
  BODY_Q_EATING_BEHAVIOR_Q09: 1,
}

export const worst_response = {
  BODY_Q_EATING_BEHAVIOR_Q01: 4,
  BODY_Q_EATING_BEHAVIOR_Q02: 4,
  BODY_Q_EATING_BEHAVIOR_Q03: 4,
  BODY_Q_EATING_BEHAVIOR_Q04: 4,
  BODY_Q_EATING_BEHAVIOR_Q05: 4,
  BODY_Q_EATING_BEHAVIOR_Q06: 4,
  BODY_Q_EATING_BEHAVIOR_Q07: 4,
  BODY_Q_EATING_BEHAVIOR_Q08: 4,
  BODY_Q_EATING_BEHAVIOR_Q09: 4,
}

export const random_response = {
  BODY_Q_EATING_BEHAVIOR_Q01: 2,
  BODY_Q_EATING_BEHAVIOR_Q02: 3,
  BODY_Q_EATING_BEHAVIOR_Q03: 1,
  BODY_Q_EATING_BEHAVIOR_Q04: 2,
  BODY_Q_EATING_BEHAVIOR_Q05: 4,
  BODY_Q_EATING_BEHAVIOR_Q06: 3,
  BODY_Q_EATING_BEHAVIOR_Q07: 2,
  BODY_Q_EATING_BEHAVIOR_Q08: 1,
  BODY_Q_EATING_BEHAVIOR_Q09: 3,
}

/**
 * 5 of 9 answered (4 missing < 50% threshold of 4.5).
 * Mean of [2,3,1,4,2] = 2.4 → imputed sum = 9 * 2.4 = 21.6 → round = 22 → Rasch = 50
 */
export const partial_response = {
  BODY_Q_EATING_BEHAVIOR_Q01: 2,
  BODY_Q_EATING_BEHAVIOR_Q02: 3,
  BODY_Q_EATING_BEHAVIOR_Q03: 1,
  BODY_Q_EATING_BEHAVIOR_Q04: 4,
  BODY_Q_EATING_BEHAVIOR_Q05: 2,
  BODY_Q_EATING_BEHAVIOR_Q06: undefined,
  BODY_Q_EATING_BEHAVIOR_Q07: undefined,
  BODY_Q_EATING_BEHAVIOR_Q08: undefined,
  BODY_Q_EATING_BEHAVIOR_Q09: undefined,
}

/**
 * 4 of 9 answered (5 missing >= 50% threshold of 4.5) → null
 */
export const too_many_missing_response = {
  BODY_Q_EATING_BEHAVIOR_Q01: 1,
  BODY_Q_EATING_BEHAVIOR_Q02: 2,
  BODY_Q_EATING_BEHAVIOR_Q03: 3,
  BODY_Q_EATING_BEHAVIOR_Q04: 4,
  BODY_Q_EATING_BEHAVIOR_Q05: undefined,
  BODY_Q_EATING_BEHAVIOR_Q06: undefined,
  BODY_Q_EATING_BEHAVIOR_Q07: undefined,
  BODY_Q_EATING_BEHAVIOR_Q08: undefined,
  BODY_Q_EATING_BEHAVIOR_Q09: undefined,
}
