type AnxietySeverityType =
  | 'Low anxiety'
  | 'Moderate anxiety'
  | 'Potentially concerning levels of anxiety'

export const BAI_INTERPRETATION_TABLE: {
  [key: string]: AnxietySeverityType
} = {
  '0': 'Low anxiety',
  '1': 'Low anxiety',
  '2': 'Low anxiety',
  '3': 'Low anxiety',
  '4': 'Low anxiety',
  '5': 'Low anxiety',
  '6': 'Low anxiety',
  '7': 'Low anxiety',
  '8': 'Low anxiety',
  '9': 'Low anxiety',
  '10': 'Low anxiety',
  '11': 'Low anxiety',
  '12': 'Low anxiety',
  '13': 'Low anxiety',
  '14': 'Low anxiety',
  '15': 'Low anxiety',
  '16': 'Low anxiety',
  '17': 'Low anxiety',
  '18': 'Low anxiety',
  '19': 'Low anxiety',
  '20': 'Low anxiety',
  '21': 'Low anxiety',
  '22': 'Moderate anxiety',
  '23': 'Moderate anxiety',
  '24': 'Moderate anxiety',
  '25': 'Moderate anxiety',
  '26': 'Moderate anxiety',
  '27': 'Moderate anxiety',
  '28': 'Moderate anxiety',
  '29': 'Moderate anxiety',
  '30': 'Moderate anxiety',
  '31': 'Moderate anxiety',
  '32': 'Moderate anxiety',
  '33': 'Moderate anxiety',
  '34': 'Moderate anxiety',
  '35': 'Moderate anxiety',
  '36': 'Potentially concerning levels of anxiety',
  '37': 'Potentially concerning levels of anxiety',
  '38': 'Potentially concerning levels of anxiety',
  '39': 'Potentially concerning levels of anxiety',
  '40': 'Potentially concerning levels of anxiety',
  '41': 'Potentially concerning levels of anxiety',
  '42': 'Potentially concerning levels of anxiety',
  '43': 'Potentially concerning levels of anxiety',
  '44': 'Potentially concerning levels of anxiety',
  '45': 'Potentially concerning levels of anxiety',
  '46': 'Potentially concerning levels of anxiety',
  '47': 'Potentially concerning levels of anxiety',
  '48': 'Potentially concerning levels of anxiety',
  '49': 'Potentially concerning levels of anxiety',
  '50': 'Potentially concerning levels of anxiety',
  '51': 'Potentially concerning levels of anxiety',
  '52': 'Potentially concerning levels of anxiety',
  '53': 'Potentially concerning levels of anxiety',
  '54': 'Potentially concerning levels of anxiety',
  '55': 'Potentially concerning levels of anxiety',
  '56': 'Potentially concerning levels of anxiety',
  '57': 'Potentially concerning levels of anxiety',
  '58': 'Potentially concerning levels of anxiety',
  '59': 'Potentially concerning levels of anxiety',
  '60': 'Potentially concerning levels of anxiety',
  '61': 'Potentially concerning levels of anxiety',
  '62': 'Potentially concerning levels of anxiety',
  '63': 'Potentially concerning levels of anxiety',
}

