type HealthImpactType = 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY HIGH'

export const CAT_INTERPRATION_TABLE: Record<string, HealthImpactType> = {
  '0': 'LOW',
  '1': 'LOW',
  '2': 'LOW',
  '3': 'LOW',
  '4': 'LOW',
  '5': 'LOW',
  '6': 'LOW',
  '7': 'LOW',
  '8': 'LOW',
  '9': 'LOW',
  '10': 'LOW',
  '11': 'MEDIUM',
  '12': 'MEDIUM',
  '13': 'MEDIUM',
  '14': 'MEDIUM',
  '15': 'MEDIUM',
  '16': 'MEDIUM',
  '17': 'MEDIUM',
  '18': 'MEDIUM',
  '19': 'MEDIUM',
  '20': 'MEDIUM',
  '21': 'HIGH',
  '22': 'HIGH',
  '23': 'HIGH',
  '24': 'HIGH',
  '25': 'HIGH',
  '26': 'HIGH',
  '27': 'HIGH',
  '28': 'HIGH',
  '29': 'HIGH',
  '30': 'HIGH',
  '31': 'VERY HIGH',
  '32': 'VERY HIGH',
  '33': 'VERY HIGH',
  '34': 'VERY HIGH',
  '35': 'VERY HIGH',
  '36': 'VERY HIGH',
  '37': 'VERY HIGH',
  '38': 'VERY HIGH',
  '39': 'VERY HIGH',
  '40': 'VERY HIGH',
}
