export const SDQ_INTERPRETATION_SCALE_IDS = [
  /**
   * Three band categorisation - Parent reported
   */
  'EMOTIONAL_PROBLEMS_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  'CONDUCT_PROBLEMS_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  'HYPERACTIVITY_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  'PEER_PROBLEMS_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  'PROSOCIAL_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  'TOTAL_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  'IMPACT_PARENT_REPORTED_THREE_BAND_CATEGORISING',
  /**
   * Three band categorisation - Teacher reported
   */
  'EMOTIONAL_PROBLEMS_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  'CONDUCT_PROBLEMS_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  'HYPERACTIVITY_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  'PEER_PROBLEMS_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  'PROSOCIAL_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  'TOTAL_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  'IMPACT_TEACHER_REPORTED_THREE_BAND_CATEGORISING',
  /**
   * Three band categorisation - Self reported
   */
  'EMOTIONAL_PROBLEMS_SELF_REPORTED_THREE_BAND_CATEGORISING',
  'CONDUCT_PROBLEMS_SELF_REPORTED_THREE_BAND_CATEGORISING',
  'HYPERACTIVITY_SELF_REPORTED_THREE_BAND_CATEGORISING',
  'PEER_PROBLEMS_SELF_REPORTED_THREE_BAND_CATEGORISING',
  'PROSOCIAL_SELF_REPORTED_THREE_BAND_CATEGORISING',
  'TOTAL_SELF_REPORTED_THREE_BAND_CATEGORISING',
  'IMPACT_SELF_REPORTED_THREE_BAND_CATEGORISING',
  /**
   * Four band categorisation - Parent reported
   */
  'EMOTIONAL_PROBLEMS_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  'CONDUCT_PROBLEMS_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  'HYPERACTIVITY_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  'PEER_PROBLEMS_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  'PROSOCIAL_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  'TOTAL_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  'IMPACT_PARENT_REPORTED_FOUR_BAND_CATEGORISING',
  /**
   * Four band categorisation - Teacher reported
   */
  'EMOTIONAL_PROBLEMS_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  'CONDUCT_PROBLEMS_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  'HYPERACTIVITY_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  'PEER_PROBLEMS_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  'PROSOCIAL_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  'TOTAL_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  'IMPACT_TEACHER_REPORTED_FOUR_BAND_CATEGORISING',
  /**
   * Four band categorisation - Self reported
   */
  'EMOTIONAL_PROBLEMS_SELF_REPORTED_FOUR_BAND_CATEGORISING',
  'CONDUCT_PROBLEMS_SELF_REPORTED_FOUR_BAND_CATEGORISING',
  'HYPERACTIVITY_SELF_REPORTED_FOUR_BAND_CATEGORISING',
  'PEER_PROBLEMS_SELF_REPORTED_FOUR_BAND_CATEGORISING',
  'PROSOCIAL_SELF_REPORTED_FOUR_BAND_CATEGORISING',
  'TOTAL_SELF_REPORTED_FOUR_BAND_CATEGORISING',
  'IMPACT_SELF_REPORTED_FOUR_BAND_CATEGORISING',
]
