export type SubscaleType =
  | 'EMOTIONAL_PROBLEMS'
  | 'CONDUCT_PROBLEMS'
  | 'HYPERACTIVITY'
  | 'PEER_PROBLEMS'
  | 'PROSOCIAL'
  | 'IMPACT_PARENT_REPORTED'
  | 'IMPACT_TEACHER_REPORTED'
  | 'IMPACT_SELF_REPORTED'

export const SDQ_SUBSCALES: Record<SubscaleType, string[]> = {
  EMOTIONAL_PROBLEMS: [
    'EMOTIONAL_PROBLEMS_Q01',
    'EMOTIONAL_PROBLEMS_Q02',
    'EMOTIONAL_PROBLEMS_Q03',
    'EMOTIONAL_PROBLEMS_Q04',
    'EMOTIONAL_PROBLEMS_Q05',
  ],
  CONDUCT_PROBLEMS: [
    'CONDUCT_PROBLEMS_Q01',
    'CONDUCT_PROBLEMS_Q02',
    'CONDUCT_PROBLEMS_Q03',
    'CONDUCT_PROBLEMS_Q04',
    'CONDUCT_PROBLEMS_Q05',
  ],
  HYPERACTIVITY: [
    'HYPERACTIVITY_Q01',
    'HYPERACTIVITY_Q02',
    'HYPERACTIVITY_Q03',
    'HYPERACTIVITY_Q04',
    'HYPERACTIVITY_Q05',
  ],
  PEER_PROBLEMS: [
    'PEER_PROBLEMS_Q01',
    'PEER_PROBLEMS_Q02',
    'PEER_PROBLEMS_Q03',
    'PEER_PROBLEMS_Q04',
    'PEER_PROBLEMS_Q05',
  ],
  PROSOCIAL: [
    'PROSOCIAL_Q01',
    'PROSOCIAL_Q02',
    'PROSOCIAL_Q03',
    'PROSOCIAL_Q04',
    'PROSOCIAL_Q05',
  ],
  IMPACT_PARENT_REPORTED: [
    'IMPACT_PARENT_Q01',
    'IMPACT_PARENT_Q02',
    'IMPACT_PARENT_Q03',
    'IMPACT_PARENT_Q04',
    'IMPACT_PARENT_Q05',
  ],
  IMPACT_TEACHER_REPORTED: [
    'IMPACT_TEACHER_Q01',
    'IMPACT_TEACHER_Q02',
    'IMPACT_TEACHER_Q03',
  ],
  IMPACT_SELF_REPORTED: [
    'IMPACT_SELF_REPORT_Q01',
    'IMPACT_SELF_REPORT_Q02',
    'IMPACT_SELF_REPORT_Q03',
    'IMPACT_SELF_REPORT_Q04',
    'IMPACT_SELF_REPORT_Q05',
  ],
}
