name: Generate Score
on:
  issues:
    types: [opened]

jobs:
  generate-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run AI Agent to generate score code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: node scripts/generate-score.mjs "${{ github.event.issue.number }}"

      - name: Execute bash to generate score files
        run: bash create_score.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git checkout -b feature/${{ github.event.issue.title }}
          git add src/scores/${{ github.event.issue.title }}
          git commit -m "Auto-generate score: ${{ github.event.issue.title }}"
          git push origin feature/${{ github.event.issue.title }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature/${{ github.event.issue.title }}
          title: "Auto-generated score: ${{ github.event.issue.title }}"
          body: "This PR was automatically generated from issue #${{ github.event.issue.number }}. Please review and make necessary adjustments."