name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  test:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Linting Typescript
        run: yarn lint

      - name: Compile Typescript
        run: yarn build

      - name: Run tests
        run: yarn test
